name: Deploy

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd spec/dummy-app
          rm Gemfile.lock
          gem install bundler
          bundle install
      - uses: akhileshns/heroku-deploy@v3.5.6 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "devise-recognise-staging"
          heroku_email: ${{secrets.HEROKU_API_KEY}}
          appdir: "spec/dummy-app"